---
title: "Project Capstone"
author: "Raj"
date: "May 17, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(dplyr)
library(ggplot2)
```

## Bank Marketing Data Analysis



```{r echo=FALSE}
#rm(bankdata)
bankdata <- read_excel("C:/DataScience/code/bank-mktg-cmpg-data.xls")
summary(bankdata)
```

#After cleaning up data and categorizing values

```{r echo=FALSE}
get_bal_category <- function(bal)
{
  if (bal <= 0)
  {
    return(1)
  }
  else if (bal > 0 & bal <= 10000)
    {
    return(2)
  }
  else if (bal > 10000 & bal <= 20000)
  {
    return(3)
  }
  else if (bal > 20000 & bal <= 30000)
  {
    return(4)
  }
  else if (bal > 30000 & bal <= 40000)
  {
    return(5)
  }
  else if (bal > 40000 & bal <= 50000)
  {
    return(6)
  }
  else if (bal > 50000 & bal <= 60000)
  {
    return(7)
  }
  else if (bal > 60000 & bal <= 70000)
  {
    return(8)
  }
  else if (bal > 70000)
  {
    return(9)
  }
  
}

get_indicator <- function(ind)
{
  #if (ind == "yes")
  #{
  #  return(1)
  #}else
  #{
  #  return(0)
  #}
  
  switch(ind,
        yes = 1,
        no = 0
        )
  
  
}

get_age_group <- function(age)
{
  if (age <= 20)
  {
    return(1)
  }
  else if (age > 20 & age <= 30)
  {
    return(2)
  }
  else if (age > 30 & age <= 40)
  {
    return(3)
  }
  else if (age > 40 & age <= 50)
  {
    return(4)
  }  
  else if (age > 50 & age <= 60)
  {
    return(5)
  }
  else if (age > 60 & age <= 70)
  {
    return(6)
  }
  else if (age > 70 & age <= 80)
  {
    return(7)
  } 
  else if (age > 80)
  {
    return(8)
  }
}

bankdata <- mutate(bankdata, bal_group=mapply(get_bal_category , bankdata$balance))
bankdata <- mutate(bankdata, age_group=mapply(get_age_group, bankdata$age))
bankdata <- mutate(bankdata, signup=mapply(get_indicator , bankdata$y))
#View(bankdata)
str(bankdata)

```


## Including Plots

Age vs Balance

```{r pressure, echo=FALSE}
ggplot(bankdata, aes(x = age, y = balance)) +
  geom_point()

```
